version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 17011996
      POSTGRES_DB: school
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-management-app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:17011996@postgres:5432/school
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  postgres_data: