version: '3.8'

services:
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://postgres:dFGzDIFSz5aGVy8@db.erobcmncvrabujsfvtqr.supabase.co:5432/postgres"
    networks:
    - app_network

networks:
  app_network:
    driver: bridge