"use client";
import { useRouter } from "next/navigation";
import Menu from "@/components/Menu";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import Link from "next/link";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({ children }) {
  const router = useRouter();

  // Exclude `/welcome` from using the layout
  if (router.pathname === "/welcome") {
    return <>{children}</>; // Render the children without the layout
  }

  return (
    <div className="h-screen flex">
      {/* Left */}
      <div className="w-[14%] md:w-[8%] lg:w-[16%] xl-w:[14%] ">
        <Link
          href={"/"}
          className="flex items-center justify-center lg:justify-start gap-2"
        >
          <Image src={"/logo.png"} width={32} height={32} alt="logo" />
          <span className="hidden lg:block">shoolname</span>
        </Link>
        <Menu />
      </div>
      {/* Right */}
      <div className="w-[86%] md:w-[92%] lg:w-[84%] xl-w[86%] bg-[#F7F8FA] overflow-y-scroll flex flex-col ">
        <Navbar />
        {children}
      </div>
    </div>
  );
}
