import 'react-calendar/dist/Calendar.css';
import './globals.css';
import 'react-big-calendar/lib/css/react-big-calendar.css';
import { ClerkProvider } from '@clerk/nextjs';
import { DatabaseProvider } from './context/DatabaseProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="font-sans">
        <ClerkProvider>
          <DatabaseProvider>  {/* ✅ Wrap the entire app with DatabaseProvider */}
            {children}
          </DatabaseProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
