import 'react-calendar/dist/Calendar.css';
import './globals.css';
import 'react-big-calendar/lib/css/react-big-calendar.css';
import { ClerkProvider } from '@clerk/nextjs';
import { DatabaseProvider } from './context/DatabaseProvider';
import { Toaster } from '@/components/ui/toaster';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="">
        <ClerkProvider frontendApi="pk_test_cHJvLWRpbmdvLTUxLmNsZXJrLmFjY291bnRzLmRldiQ">
          <DatabaseProvider> 
            {children}
            <Toaster />

          </DatabaseProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
